version: "3.7"

services:
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend/:/backend
    command: "uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - memcached

#  frontend:
#    build: ./frontend

  memcached:
    image: memcached:1.6.23
    hostname: "${MEMCACHED_HOST}"
    restart: always
    ports:
      - "${MEMCACHED_PORT}:11211"
    environment:
      - MEMCACHED_USERNAME=${MEMCACHED_USERNAME}
      - MEMCACHED_PASSWORD=${MEMCACHED_PASSWORD}
