version: "3.7"

services:
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend/:/backend
    command: "uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env

#  frontend:
#    build: ./frontend
