[tool.poetry]
name = "bot"
version = "0.1.0"
description = ""
authors = ["Grigory Malanchuk <grigorymalanchuk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.10.0"
python-dotenv = "^1.0.1"
flake8 = "^7.1.0"
black = "^24.4.2"
isort = "^5.13.2"
loguru = "^0.7.2"
pre-commit = "^3.7.1"
spotipy = "^2.24.0"
yt-dlp = "^2024.7.9"
youtube-search-python = "^1.6.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
skip = ["venv"]
lines_after_imports = 2
